// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
    TRelationship extends
        | prismic.CustomTypeModelFetchCustomTypeLevel1
        | prismic.CustomTypeModelFetchCustomTypeLevel2
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2,
    TData extends Record<
        string,
        | prismic.AnyRegularField
        | prismic.GroupField
        | prismic.NestedGroupField
        | prismic.SliceZone
    >,
    TLang extends string,
> =
    // Content relationship fields
    {
        [
            TSubRelationship in Extract<
                TRelationship['fields'][number],
                prismic.CustomTypeModelFetchContentRelationshipLevel1
            > as TSubRelationship['id']
        ]: ContentRelationshipFieldWithData<
            TSubRelationship['customtypes'],
            TLang
        >;
    } & // Group
    {
        [
            TGroup in Extract<
                TRelationship['fields'][number],
                | prismic.CustomTypeModelFetchGroupLevel1
                | prismic.CustomTypeModelFetchGroupLevel2
            > as TGroup['id']
        ]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
            ? prismic.GroupField<
                  PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
              >
            : never;
    } & // Other fields
    {
        [
            TFieldKey in Extract<TRelationship['fields'][number], string>
        ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
    };

type ContentRelationshipFieldWithData<
    TCustomType extends
        | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
        | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
    TLang extends string = string,
> = {
    [
        ID in Exclude<TCustomType[number], string>['id']
    ]: prismic.ContentRelationshipField<
        ID,
        TLang,
        PickContentRelationshipFieldData<
            Extract<TCustomType[number], { id: ID }>,
            Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
            TLang
        >
    >;
}[Exclude<TCustomType[number], string>['id']];

type BlogPostDocumentDataBodySlice = RichTextSlice | HeadingSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
    /**
     * Title field in *Blog Post*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/fields/rich-text
     */
    title: prismic.RichTextField;

    /**
     * Cover image field in *Blog Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/fields/image
     */
    image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *Blog Post*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/slices
     */
    body: prismic.SliceZone<BlogPostDocumentDataBodySlice>; /**
     * Meta Title field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.meta_title
     * - **Tab**: Metadata
     * - **Documentation**: https://prismic.io/docs/fields/text
     */
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.meta_description
     * - **Tab**: Metadata
     * - **Documentation**: https://prismic.io/docs/fields/text
     */
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Blog Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.meta_image
     * - **Tab**: Metadata
     * - **Documentation**: https://prismic.io/docs/fields/image
     */
    meta_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<BlogPostDocumentData>,
        'blog_post',
        Lang
    >;

export type AllDocumentTypes = BlogPostDocument;

/**
 * Primary content in *CodeBlock → Default → Primary*
 */
export interface CodeBlockSliceDefaultPrimary {
    /**
     * Code field in *CodeBlock → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Paste your code here
     * - **API ID Path**: code_block.default.primary.code
     * - **Documentation**: https://prismic.io/docs/fields/text
     */
    code: prismic.KeyTextField;

    /**
     * Language field in *CodeBlock → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: plaintext
     * - **API ID Path**: code_block.default.primary.language
     * - **Documentation**: https://prismic.io/docs/fields/select
     */
    language: prismic.SelectField<
        | 'plaintext'
        | 'javascript'
        | 'typescript'
        | 'jsx'
        | 'tsx'
        | 'css'
        | 'json'
        | 'bash'
        | 'markdown',
        'filled'
    >;

    /**
     * Filename (optional) field in *CodeBlock → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: code_block.default.primary.filename
     * - **Documentation**: https://prismic.io/docs/fields/text
     */
    filename: prismic.KeyTextField;
}

/**
 * Default variation for CodeBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CodeBlockSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<CodeBlockSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *CodeBlock*
 */
type CodeBlockSliceVariation = CodeBlockSliceDefault;

/**
 * CodeBlock Shared Slice
 *
 * - **API ID**: `code_block`
 * - **Description**: Syntax-highlighted code
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CodeBlockSlice = prismic.SharedSlice<
    'code_block',
    CodeBlockSliceVariation
>;

/**
 * Primary content in *Divider → Default → Primary*
 */
export interface DividerSliceDefaultPrimary {
    /**
     * Style field in *Divider → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: plain
     * - **API ID Path**: divider.default.primary.style
     * - **Documentation**: https://prismic.io/docs/fields/select
     */
    style: prismic.SelectField<'plain' | 'asterism', 'filled'>;
}

/**
 * Default variation for Divider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DividerSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<DividerSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *Divider*
 */
type DividerSliceVariation = DividerSliceDefault;

/**
 * Divider Shared Slice
 *
 * - **API ID**: `divider`
 * - **Description**: Section separator
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DividerSlice = prismic.SharedSlice<
    'divider',
    DividerSliceVariation
>;

/**
 * Primary content in *Heading → Default → Primary*
 */
export interface HeadingSliceDefaultPrimary {
    /**
     * Heading field in *Heading → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: heading.default.primary.heading
     * - **Documentation**: https://prismic.io/docs/fields/rich-text
     */
    heading: prismic.RichTextField;

    /**
     * Label (optional) field in *Heading → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: heading.default.primary.label
     * - **Documentation**: https://prismic.io/docs/fields/text
     */
    label: prismic.KeyTextField;
}

/**
 * Default variation for Heading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadingSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<HeadingSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *Heading*
 */
type HeadingSliceVariation = HeadingSliceDefault;

/**
 * Heading Shared Slice
 *
 * - **API ID**: `heading`
 * - **Description**: A section heading with an optional label
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadingSlice = prismic.SharedSlice<
    'heading',
    HeadingSliceVariation
>;

/**
 * Primary content in *Images → Items*
 */
export interface ImagesSliceDefaultItem {
    /**
     * Image field in *Images → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: images.items[].image
     * - **Documentation**: https://prismic.io/docs/fields/image
     */
    image: prismic.ImageField<never>;

    /**
     * Caption field in *Images → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: images.items[].caption
     * - **Documentation**: https://prismic.io/docs/fields/text
     */
    caption: prismic.KeyTextField;
}

/**
 * Default variation for Images Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImagesSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<ImagesSliceDefaultItem>
>;

/**
 * Slice variation for *Images*
 */
type ImagesSliceVariation = ImagesSliceDefault;

/**
 * Images Shared Slice
 *
 * - **API ID**: `images`
 * - **Description**: One or more images with optional captions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImagesSlice = prismic.SharedSlice<'images', ImagesSliceVariation>;

/**
 * Primary content in *Quote → Default → Primary*
 */
export interface QuoteSliceDefaultPrimary {
    /**
     * Quote field in *Quote → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: quote.default.primary.quote
     * - **Documentation**: https://prismic.io/docs/fields/rich-text
     */
    quote: prismic.RichTextField;

    /**
     * Attribution (optional) field in *Quote → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: quote.default.primary.attribution
     * - **Documentation**: https://prismic.io/docs/fields/text
     */
    attribution: prismic.KeyTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<QuoteSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Pull quote with optional attribution
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteSlice = prismic.SharedSlice<'quote', QuoteSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
    /**
     * Content field in *RichText → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: rich_text.default.primary.content
     * - **Documentation**: https://prismic.io/docs/fields/rich-text
     */
    content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<RichTextSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: Headings, text, links, and embeds
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
    'rich_text',
    RichTextSliceVariation
>;

declare module '@prismicio/client' {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig
        ): prismic.Client<AllDocumentTypes>;
    }

    interface CreateWriteClient {
        (
            repositoryNameOrEndpoint: string,
            options: prismic.WriteClientConfig
        ): prismic.WriteClient<AllDocumentTypes>;
    }

    interface CreateMigration {
        (): prismic.Migration<AllDocumentTypes>;
    }

    namespace Content {
        export type {
            BlogPostDocument,
            BlogPostDocumentData,
            BlogPostDocumentDataBodySlice,
            AllDocumentTypes,
            CodeBlockSlice,
            CodeBlockSliceDefaultPrimary,
            CodeBlockSliceVariation,
            CodeBlockSliceDefault,
            DividerSlice,
            DividerSliceDefaultPrimary,
            DividerSliceVariation,
            DividerSliceDefault,
            HeadingSlice,
            HeadingSliceDefaultPrimary,
            HeadingSliceVariation,
            HeadingSliceDefault,
            ImagesSlice,
            ImagesSliceDefaultItem,
            ImagesSliceVariation,
            ImagesSliceDefault,
            QuoteSlice,
            QuoteSliceDefaultPrimary,
            QuoteSliceVariation,
            QuoteSliceDefault,
            RichTextSlice,
            RichTextSliceDefaultPrimary,
            RichTextSliceVariation,
            RichTextSliceDefault,
        };
    }
}
